services:
  lastfm:
    build: .
    image: lastfm-session-prediction:latest
    working_dir: /app
    # Expose Streamlit port
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - DATA_PATH=""
    command: ["streamlit", "run", "app/main_page_study_case.py", "--server.port=8501", "--server.address=0.0.0.0"]
    restart: unless-stopped
