services:
  lastfm:
    build: .
    image: lastfm:latest
    working_dir: /app
    # Expose Streamlit port
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_APP=streamlit/main_page_study_case.py
    command: ["streamlit", "run", "${STREAMLIT_APP}", "--server.port=8501", "--server.address=0.0.0.0"]
    # Remove the `volumes` line for immutable/deployable images.
    volumes:
      - ./:/app
    restart: unless-stopped
